name: Automated Preprocessing Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install pandas numpy scikit-learn imbalanced-learn
          
      - name: Run preprocessing
        run: |
          python << 'EOF'
          import pandas as pd
          import sys
          import importlib.util
          
          spec = importlib.util.spec_from_file_location(
              "automate_module", 
              "preprocessing/automate_Abiyyu_Rasyiq_Muhadzzib.py"
          )
          automate_module = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(automate_module)
          preprocess_data = automate_module.preprocess_data
          
          df = pd.read_csv('loan_data.csv')
          X_train, X_test, y_train, y_test, _ = preprocess_data(df)
          
          X_train['loan_status'] = y_train.values
          X_test['loan_status'] = y_test.values
          df_preprocessed = pd.concat([X_train, X_test], ignore_index=True)
          output_path = 'preprocessing/loan_data_preprocessed.csv'
          df_preprocessed.to_csv(output_path, index=False)
          
          print(f'Preprocessing completed: {df_preprocessed.shape}')
          EOF
          
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/loan_data_preprocessed.csv
          git diff --staged --quiet || git commit -m "Auto: Update preprocessed dataset [skip ci]"
          git push
