name: Automated Preprocessing Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn imbalanced-learn
          
      - name: Run preprocessing
        run: |
          cat << 'EOF' > run_preprocess.py
          import pandas as pd
          import sys
          sys.path.append('preprocessing')
          from automate_Abiyyu_Rasyiq_Muhadzzib import preprocess_data
          
          print('='*60)
          print('Starting Automated Preprocessing Pipeline')
          print('='*60)
          
          # Load raw data
          print('\n[1/4] Loading raw dataset...')
          df = pd.read_csv('loan_data.csv')
          print(f'✓ Raw data loaded: {df.shape}')
          
          # Run preprocessing
          print('\n[2/4] Running preprocessing...')
          X_train, X_test, y_train, y_test, fitted_objects = preprocess_data(df)
          print(f'✓ Preprocessing completed')
          print(f'  - Train shape: {X_train.shape}')
          print(f'  - Test shape: {X_test.shape}')
          
          # Combine processed data
          print('\n[3/4] Combining processed data...')
          X_train['loan_status'] = y_train.values
          X_test['loan_status'] = y_test.values
          df_preprocessed = pd.concat([X_train, X_test], axis=0, ignore_index=True)
          print(f'✓ Combined data shape: {df_preprocessed.shape}')
          
          # Save preprocessed data
          print('\n[4/4] Saving preprocessed dataset...')
          df_preprocessed.to_csv('loan_data_preprocessed.csv', index=False)
          print('✓ Preprocessed data saved: loan_data_preprocessed.csv')
          
          print('\n' + '='*60)
          print('Pipeline completed successfully!')
          print('='*60)
          EOF
          
          python run_preprocess.py
          
      - name: Commit preprocessed data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add loan_data_preprocessed.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto: Update preprocessed dataset [skip ci]"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
